//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOC2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AOC2020.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1753
        ///1976
        ///1574
        ///308
        ///1384
        ///1191
        ///1731
        ///1829
        ///1658
        ///1908
        ///1663
        ///2001
        ///1298
        ///1888
        ///1134
        ///1213
        ///965
        ///2009
        ///1071
        ///1591
        ///1402
        ///1184
        ///1836
        ///1536
        ///1038
        ///1871
        ///1354
        ///1149
        ///1863
        ///1728
        ///1896
        ///1599
        ///1556
        ///1222
        ///1909
        ///1858
        ///1754
        ///1947
        ///1907
        ///1656
        ///1135
        ///1845
        ///1504
        ///1473
        ///1401
        ///1700
        ///1067
        ///1790
        ///1783
        ///1539
        ///1087
        ///1614
        ///1856
        ///1895
        ///1564
        ///1106
        ///1204
        ///1492
        ///1361
        ///1897
        ///1977
        ///1210
        ///1867
        ///1797
        ///1232
        ///1148
        ///1520
        ///1989
        ///210
        ///1259
        ///570
        ///1512
        ///1894
        ///1309
        ///1154
        ///1327
        ///1817
        ///1875
        ///1702
        ///1885
        ///1664
        ///1220
        ///1208
        ///2000
        ///1178
        ///1423
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jmp +301
        ///acc +27
        ///nop +299
        ///jmp +168
        ///acc +0
        ///acc +48
        ///acc -5
        ///jmp +420
        ///jmp +155
        ///acc -16
        ///acc -15
        ///nop +582
        ///acc -5
        ///jmp +490
        ///acc +10
        ///nop +300
        ///acc -2
        ///acc -1
        ///jmp +252
        ///jmp +2
        ///jmp +234
        ///acc +36
        ///acc +50
        ///jmp +564
        ///jmp +102
        ///jmp +473
        ///acc +37
        ///acc +1
        ///acc +20
        ///jmp +355
        ///acc +28
        ///acc -14
        ///acc +22
        ///jmp +329
        ///acc +44
        ///jmp +1
        ///jmp +23
        ///nop +312
        ///jmp +251
        ///acc +12
        ///acc +39
        ///acc +33
        ///jmp -21
        ///acc +28
        ///acc +14
        ///acc +42
        ///acc +33
        ///jmp +502
        ///jmp +123
        ///acc +24
        ///jmp +11
        ///acc -8
        ///nop +218
        ///nop +516
        ///jmp +244
        ///jmp  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EighthInput {
            get {
                return ResourceManager.GetString("EighthInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLLLLLLLLLLLLLLLLLLLLLL.LLLLLLL.L.LLLLL.LLLL.LLLLLLLLL..LLL.LLLLLLLLLLLLLL.LLLLLLLLL.LLL.LLLLLL
        ///LLLLLLLLLL.L.LLLLLLL.LL.LLLLLLL.LLLLLLLL.LLLLLLLLLLLLL.LLLLLLLLLLL.LLLLLLLL.LLLLLLLLLLLL.LLLLLL
        ///LLLLLLLL.L.LLLLLLLLLLLL.LLLLLLL.LLLLLL.LLLLL.LLLLLLLLL.LLLLLLLLLLL.LLLLLLLLLLLLLLLL.LLLL.LLLLLL
        ///.LLLLLLLLLLLLLLLLL.LLLL.LLLLLLL.LLLLLL.LLLLL.LLL.LLLLLLLLLL.LLLLLL.LLLLLLLL.LLLLLL.LLLLL.LLLLLL
        ///LLLLLLLLLLLLLLLLLLLLLLL.LLLLLLL.LLL.LLLLL.LL.LLLLLLLLL.LLLL.LLLLLL.LLLLLLLL.LLLLLLL.LLLL.LLLLLL
        ///LLL.LL..L..L.LL.L.L........ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EleventhInput {
            get {
                return ResourceManager.GetString("EleventhInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.LL.LL.LL
        ///LLLLLLL.LL
        ///L.L.L..L..
        ///LLLL.LL.LL
        ///L.LL.LL.LL
        ///L.LLLLL.LL
        ///..L.L.....
        ///LLLLLLLLLL
        ///L.LLLLLL.L
        ///L.LLLLL.L.
        /// </summary>
        internal static string EleventhInputTest {
            get {
                return ResourceManager.GetString("EleventhInputTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFFFBFFRLR
        ///FBBBFFBRRL
        ///FFBFBFFRRR
        ///FBBFBFFRRR
        ///BBBFFFFLLR
        ///FFBFBBFRRR
        ///BFFBBFFLRL
        ///BBBFBBFLRR
        ///BFFBFBFLRR
        ///BBBFFBFLLL
        ///BFBFBBBRRR
        ///FBBBBBFLRR
        ///BBFFBBFRRL
        ///BFBBBBBRLR
        ///FBBFFFFRLR
        ///BBFFBFFRRL
        ///FBBFFFBRRR
        ///FFBBBBFRRL
        ///BFBBBFFRRR
        ///BBBFBFBRRR
        ///FBFFBFBRLR
        ///BFFBBFBLLL
        ///BBFFFFFRRL
        ///FBBBBFBRLR
        ///FBBBBBFRLR
        ///BFFBBBFLRR
        ///FBFBFBFLLR
        ///FFBFFFBRRR
        ///BBBFFBBLRR
        ///BBBFFBBLRL
        ///BBFBFFBLRR
        ///BBBFFFFRRL
        ///FBFFFBFLRR
        ///BBFBBBFRLL
        ///BBBFFBFLRR
        ///FBFFFFBLRR
        ///FBBBBBFLRL
        ///BBFFFBBRRL
        ///BBFFBFBLRL
        ///BBBFBBFRLR
        ///FFBBFFFRRL
        ///BBFBBBFLRL
        ///BFBBFFBR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FifthInput {
            get {
                return ResourceManager.GetString("FifthInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mask = 0X0X1110X1010X1X10010X0011010X100110
        ///mem[40190] = 23031023
        ///mem[13516] = 384739600
        ///mask = XX00111XX1010X0110011110X1XX110010X1
        ///mem[12490] = 3068791
        ///mem[61106] = 3432
        ///mem[48664] = 204086010
        ///mask = X0X01101010001X10X01X1X1101010100000
        ///mem[43153] = 831935068
        ///mem[61625] = 5711
        ///mem[43599] = 125635699
        ///mem[36959] = 776266806
        ///mask = 0000111XX1010101X001XXX1X01000001110
        ///mem[48186] = 257869
        ///mem[59392] = 738895
        ///mem[65386] = 4054824
        ///mem[10464] = 2127
        ///mem[13157] = 3065832
        ///mem[32527] = 5148099
        ///me [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FourteenthInput {
            get {
                return ResourceManager.GetString("FourteenthInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mask = 000000000000000000000000000000X1001X
        ///mem[42] = 100
        ///mask = 00000000000000000000000000000000X0XX
        ///mem[26] = 1.
        /// </summary>
        internal static string FourteenthInputTest {
            get {
                return ResourceManager.GetString("FourteenthInputTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byr:2024 iyr:2016
        ///eyr:2034 ecl:zzz pid:985592671 hcl:033b48
        ///hgt:181 cid:166
        ///
        ///hgt:66cm
        ///pid:152cm
        ///hcl:cfb18a eyr:1947
        ///byr:2020 ecl:zzz iyr:2029
        ///
        ///ecl:gry hcl:#888785 eyr:2023 cid:63
        ///iyr:2019 hgt:177cm
        ///pid:656793259
        ///
        ///pid:#5e832a
        ///ecl:dne hcl:#7d3b0c byr:2018 eyr:1928 hgt:61cm iyr:1936 cid:241
        ///
        ///hcl:#888785 ecl:oth eyr:2025
        ///pid:597580472
        ///iyr:2017 hgt:187cm byr:1957 cid:247
        ///
        ///eyr:2029 cid:145 iyr:2026 pid:178cm hgt:162in ecl:gry
        ///hcl:#a5d09f byr:2002
        ///
        ///eyr:2024
        ///ecl:amb
        ///pid:349191561 iyr:2018 h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FourthInput {
            get {
                return ResourceManager.GetString("FourthInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-14 b: bbbbbbbbbbbbbbbbbbb
        ///3-14 v: vvpvvvmvvvvvvvv
        ///2-5 m: mfvxmmm
        ///15-20 z: zdzzzrjzzzdpzzdzzzzz
        ///6-8 g: tggjggggrg
        ///2-3 l: nlllw
        ///1-5 j: jjjjj
        ///4-5 t: prttt
        ///2-4 v: vvrqzp
        ///4-6 v: vvvvvqvvv
        ///7-8 d: mpntdwkd
        ///2-12 w: jwkfktkbthcwvfrkwgz
        ///12-16 j: jjjjpjjmdhjjdjjjjjjj
        ///10-11 f: fffffffffff
        ///3-20 n: pbclshqmxtkmgsmztjlm
        ///11-12 q: qqqqxqqqqqqqwqrxqs
        ///5-6 p: hppvnppcvqf
        ///10-11 k: kckkrbkxtknhkkkk
        ///5-7 m: kmmgxgmnnpzrzmgsbm
        ///10-17 b: bbbbbbbbbbbbbbbbrbbb
        ///5-7 v: vvvvtqvvvv
        ///6-8 g: gggggpglgzgg
        ///8-16 q: fqtqqq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14
        ///9
        ///43
        ///18
        ///13
        ///24
        ///3
        ///38
        ///33
        ///8
        ///41
        ///4
        ///32
        ///15
        ///31
        ///44
        ///17
        ///34
        ///21
        ///10
        ///50
        ///37
        ///2
        ///23
        ///6
        ///47
        ///5
        ///9
        ///11
        ///16
        ///12
        ///18
        ///7
        ///13
        ///26
        ///14
        ///19
        ///8
        ///20
        ///15
        ///29
        ///58
        ///17
        ///22
        ///21
        ///24
        ///25
        ///10
        ///27
        ///31
        ///33
        ///23
        ///28
        ///30
        ///34
        ///32
        ///35
        ///38
        ///49
        ///18
        ///26
        ///36
        ///37
        ///47
        ///39
        ///56
        ///40
        ///42
        ///43
        ///41
        ///44
        ///45
        ///46
        ///48
        ///50
        ///51
        ///53
        ///79
        ///73
        ///69
        ///117
        ///54
        ///55
        ///90
        ///57
        ///62
        ///75
        ///114
        ///85
        ///94
        ///110
        ///81
        ///98
        ///153
        ///86
        ///89
        ///204
        ///96
        ///101
        ///103
        ///104
        ///152
        ///169
        ///124
        ///135
        ///109
        ///143
        ///171
        ///119
        ///132
        ///137
        ///207
        ///166
        ///167
        ///184
        ///185
        ///170
        ///175
        ///182
        ///187
        ///190
        ///197
        ///233
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NinthInput {
            get {
                return ResourceManager.GetString("NinthInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pale chartreuse bags contain 3 faded orange bags.
        ///drab gold bags contain 5 dark aqua bags.
        ///mirrored magenta bags contain 3 dotted violet bags.
        ///posh black bags contain 3 dark lavender bags, 3 mirrored coral bags, 1 dotted chartreuse bag.
        ///striped yellow bags contain 5 pale red bags, 2 light lime bags, 5 clear indigo bags.
        ///bright aqua bags contain 2 vibrant orange bags, 4 clear lavender bags, 1 pale gray bag.
        ///dim silver bags contain 2 bright blue bags, 3 faded olive bags, 1 faded cyan bag.
        ///light beige b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeventhInput {
            get {
                return ResourceManager.GetString("SeventhInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onitvpuwxqczlmkabsjrgedfy
        ///epdjqbxlnimfaowtzgsyku
        ///pejglyqnwuaodzsbmfxikt
        ///ojkpytdhignxuqebzlwsfma
        ///gfadqolubinjxtkwpemszy
        ///
        ///i
        ///x
        ///i
        ///i
        ///
        ///nmtyqwsoglva
        ///nyvtsgwmlaoq
        ///ysgmlnwvatqo
        ///nvgdamotqyslw
        ///ylmgtaqsnvow
        ///
        ///uoqwrdpbntje
        ///cqpjnou
        ///jnupyoq
        ///npojuqs
        ///
        ///tbsafengq
        ///eabqsftgndmx
        ///beaintysgqhof
        ///
        ///ygtdfwuaorvchpnqzjlkbs
        ///fatqvskwudbljphryogc
        ///
        ///jgewimpbkdaoslr
        ///ypxzgdwqteshnau
        ///
        ///vdytrl
        ///rcltq
        ///ztlmkoi
        ///tylr
        ///gtlba
        ///
        ///oxgpa
        ///ogaxp
        ///pgoxa
        ///
        ///edi
        ///jtm
        ///b
        ///jmug
        ///
        ///deoptcxnjhrqu
        ///termcldofphxv
        ///ckgbwhedpsroxt
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SixthInput {
            get {
                return ResourceManager.GetString("SixthInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 178
        ///135
        ///78
        ///181
        ///137
        ///16
        ///74
        ///11
        ///142
        ///109
        ///148
        ///108
        ///151
        ///184
        ///121
        ///58
        ///110
        ///52
        ///169
        ///128
        ///2
        ///119
        ///38
        ///136
        ///25
        ///26
        ///73
        ///157
        ///153
        ///7
        ///19
        ///160
        ///4
        ///80
        ///10
        ///51
        ///1
        ///131
        ///55
        ///86
        ///87
        ///21
        ///46
        ///88
        ///173
        ///71
        ///64
        ///114
        ///120
        ///167
        ///172
        ///145
        ///130
        ///33
        ///20
        ///190
        ///35
        ///79
        ///162
        ///122
        ///98
        ///177
        ///179
        ///68
        ///48
        ///118
        ///125
        ///192
        ///174
        ///99
        ///152
        ///3
        ///89
        ///105
        ///180
        ///191
        ///61
        ///13
        ///90
        ///129
        ///47
        ///138
        ///67
        ///115
        ///44
        ///59
        ///60
        ///95
        ///93
        ///166
        ///154
        ///101
        ///34
        ///113
        ///139
        ///77
        ///94
        ///161
        ///187
        ///45
        ///22
        ///12
        ///163
        ///41
        ///27
        ///132
        ///30
        ///143
        ///168
        ///144
        ///83
        ///100
        ///102
        ///72.
        /// </summary>
        internal static string TenthInput {
            get {
                return ResourceManager.GetString("TenthInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .........###......#...#.......#
        ///.#.#...........#..#..#.........
        ///#.......#.................#....
        ///.........#.#.........#......###
        ///.....#......##...##............
        ///...##...#......#.....#.....##..
        ///#.#..#....#...#....#......#....
        ///........##.....#.....#.#.......
        ///......#.....#......#...##.#....
        ///...####...#.......##.....#.#...
        ///.........#....#......##........
        ///..##...........###.#...........
        ///.....#............#............
        ///#.#..#..##........#.....#..#...
        ///.....................#....##..#
        ///...........##.... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThirdInput {
            get {
                return ResourceManager.GetString("ThirdInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1009310
        ///19,x,x,x,x,x,x,x,x,x,x,x,x,37,x,x,x,x,x,599,x,29,x,x,x,x,x,x,x,x,x,x,x,x,x,x,17,x,x,x,x,x,23,x,x,x,x,x,x,x,761,x,x,x,x,x,x,x,x,x,41,x,x,13.
        /// </summary>
        internal static string ThirteenthInput {
            get {
                return ResourceManager.GetString("ThirteenthInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123
        ///1789,37,47,1889.
        /// </summary>
        internal static string ThirteenthInputTest {
            get {
                return ResourceManager.GetString("ThirteenthInputTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123
        ///1789,37,47,1889.
        /// </summary>
        internal static string ThirteenthInputTest1 {
            get {
                return ResourceManager.GetString("ThirteenthInputTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F8
        ///N2
        ///F32
        ///F17
        ///E4
        ///N4
        ///R90
        ///S2
        ///R90
        ///E3
        ///L90
        ///N5
        ///E2
        ///N2
        ///W5
        ///F78
        ///L180
        ///F19
        ///R90
        ///S1
        ///E2
        ///L180
        ///E1
        ///S5
        ///E4
        ///F62
        ///R180
        ///F16
        ///S2
        ///F8
        ///R180
        ///S1
        ///L90
        ///E4
        ///R90
        ///S3
        ///E5
        ///R180
        ///F87
        ///N2
        ///E2
        ///R90
        ///N2
        ///F2
        ///R90
        ///N5
        ///W4
        ///L90
        ///F42
        ///N1
        ///F93
        ///F87
        ///E2
        ///S4
        ///F73
        ///L270
        ///S2
        ///W3
        ///F48
        ///W5
        ///L180
        ///N1
        ///F53
        ///R90
        ///S2
        ///R90
        ///N2
        ///E2
        ///S5
        ///W3
        ///R90
        ///E2
        ///R90
        ///W1
        ///L180
        ///F29
        ///W1
        ///F56
        ///R90
        ///F34
        ///F74
        ///S1
        ///R90
        ///L90
        ///W4
        ///L90
        ///W5
        ///L90
        ///W1
        ///L90
        ///N5
        ///E2
        ///S2
        ///F58
        ///N5
        ///L90
        ///S4
        ///L90
        ///R270
        ///W4
        ///S4
        ///E3
        ///R180
        ///S4
        ///W3
        ///R90
        ///F36
        ///R90
        ///W1
        ///F73
        ///S4
        ///E1
        ///L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwelfthInput {
            get {
                return ResourceManager.GetString("TwelfthInput", resourceCulture);
            }
        }
    }
}
