//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOC2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AOC2020.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1753
        ///1976
        ///1574
        ///308
        ///1384
        ///1191
        ///1731
        ///1829
        ///1658
        ///1908
        ///1663
        ///2001
        ///1298
        ///1888
        ///1134
        ///1213
        ///965
        ///2009
        ///1071
        ///1591
        ///1402
        ///1184
        ///1836
        ///1536
        ///1038
        ///1871
        ///1354
        ///1149
        ///1863
        ///1728
        ///1896
        ///1599
        ///1556
        ///1222
        ///1909
        ///1858
        ///1754
        ///1947
        ///1907
        ///1656
        ///1135
        ///1845
        ///1504
        ///1473
        ///1401
        ///1700
        ///1067
        ///1790
        ///1783
        ///1539
        ///1087
        ///1614
        ///1856
        ///1895
        ///1564
        ///1106
        ///1204
        ///1492
        ///1361
        ///1897
        ///1977
        ///1210
        ///1867
        ///1797
        ///1232
        ///1148
        ///1520
        ///1989
        ///210
        ///1259
        ///570
        ///1512
        ///1894
        ///1309
        ///1154
        ///1327
        ///1817
        ///1875
        ///1702
        ///1885
        ///1664
        ///1220
        ///1208
        ///2000
        ///1178
        ///1423
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFFFBFFRLR
        ///FBBBFFBRRL
        ///FFBFBFFRRR
        ///FBBFBFFRRR
        ///BBBFFFFLLR
        ///FFBFBBFRRR
        ///BFFBBFFLRL
        ///BBBFBBFLRR
        ///BFFBFBFLRR
        ///BBBFFBFLLL
        ///BFBFBBBRRR
        ///FBBBBBFLRR
        ///BBFFBBFRRL
        ///BFBBBBBRLR
        ///FBBFFFFRLR
        ///BBFFBFFRRL
        ///FBBFFFBRRR
        ///FFBBBBFRRL
        ///BFBBBFFRRR
        ///BBBFBFBRRR
        ///FBFFBFBRLR
        ///BFFBBFBLLL
        ///BBFFFFFRRL
        ///FBBBBFBRLR
        ///FBBBBBFRLR
        ///BFFBBBFLRR
        ///FBFBFBFLLR
        ///FFBFFFBRRR
        ///BBBFFBBLRR
        ///BBBFFBBLRL
        ///BBFBFFBLRR
        ///BBBFFFFRRL
        ///FBFFFBFLRR
        ///BBFBBBFRLL
        ///BBBFFBFLRR
        ///FBFFFFBLRR
        ///FBBBBBFLRL
        ///BBFFFBBRRL
        ///BBFFBFBLRL
        ///BBBFBBFRLR
        ///FFBBFFFRRL
        ///BBFBBBFLRL
        ///BFBBFFBR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FifthInput {
            get {
                return ResourceManager.GetString("FifthInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byr:2024 iyr:2016
        ///eyr:2034 ecl:zzz pid:985592671 hcl:033b48
        ///hgt:181 cid:166
        ///
        ///hgt:66cm
        ///pid:152cm
        ///hcl:cfb18a eyr:1947
        ///byr:2020 ecl:zzz iyr:2029
        ///
        ///ecl:gry hcl:#888785 eyr:2023 cid:63
        ///iyr:2019 hgt:177cm
        ///pid:656793259
        ///
        ///pid:#5e832a
        ///ecl:dne hcl:#7d3b0c byr:2018 eyr:1928 hgt:61cm iyr:1936 cid:241
        ///
        ///hcl:#888785 ecl:oth eyr:2025
        ///pid:597580472
        ///iyr:2017 hgt:187cm byr:1957 cid:247
        ///
        ///eyr:2029 cid:145 iyr:2026 pid:178cm hgt:162in ecl:gry
        ///hcl:#a5d09f byr:2002
        ///
        ///eyr:2024
        ///ecl:amb
        ///pid:349191561 iyr:2018 h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FourthInput {
            get {
                return ResourceManager.GetString("FourthInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-14 b: bbbbbbbbbbbbbbbbbbb
        ///3-14 v: vvpvvvmvvvvvvvv
        ///2-5 m: mfvxmmm
        ///15-20 z: zdzzzrjzzzdpzzdzzzzz
        ///6-8 g: tggjggggrg
        ///2-3 l: nlllw
        ///1-5 j: jjjjj
        ///4-5 t: prttt
        ///2-4 v: vvrqzp
        ///4-6 v: vvvvvqvvv
        ///7-8 d: mpntdwkd
        ///2-12 w: jwkfktkbthcwvfrkwgz
        ///12-16 j: jjjjpjjmdhjjdjjjjjjj
        ///10-11 f: fffffffffff
        ///3-20 n: pbclshqmxtkmgsmztjlm
        ///11-12 q: qqqqxqqqqqqqwqrxqs
        ///5-6 p: hppvnppcvqf
        ///10-11 k: kckkrbkxtknhkkkk
        ///5-7 m: kmmgxgmnnpzrzmgsbm
        ///10-17 b: bbbbbbbbbbbbbbbbrbbb
        ///5-7 v: vvvvtqvvvv
        ///6-8 g: gggggpglgzgg
        ///8-16 q: fqtqqq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .........###......#...#.......#
        ///.#.#...........#..#..#.........
        ///#.......#.................#....
        ///.........#.#.........#......###
        ///.....#......##...##............
        ///...##...#......#.....#.....##..
        ///#.#..#....#...#....#......#....
        ///........##.....#.....#.#.......
        ///......#.....#......#...##.#....
        ///...####...#.......##.....#.#...
        ///.........#....#......##........
        ///..##...........###.#...........
        ///.....#............#............
        ///#.#..#..##........#.....#..#...
        ///.....................#....##..#
        ///...........##.... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThirdInput {
            get {
                return ResourceManager.GetString("ThirdInput", resourceCulture);
            }
        }
    }
}
