//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35
        ///20
        ///15
        ///25
        ///47
        ///40
        ///62
        ///55
        ///65
        ///95
        ///102
        ///117
        ///150
        ///182
        ///127
        ///219
        ///299
        ///277
        ///309
        ///576.
        /// </summary>
        internal static string NinthTestInput {
            get {
                return ResourceManager.GetString("NinthTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16
        ///10
        ///15
        ///5
        ///1
        ///11
        ///7
        ///19
        ///6
        ///12
        ///4.
        /// </summary>
        internal static string TenthTestInput {
            get {
                return ResourceManager.GetString("TenthTestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28
        ///33
        ///18
        ///42
        ///31
        ///14
        ///46
        ///20
        ///48
        ///47
        ///24
        ///23
        ///49
        ///45
        ///19
        ///38
        ///39
        ///11
        ///1
        ///32
        ///25
        ///35
        ///8
        ///17
        ///7
        ///9
        ///4
        ///2
        ///34
        ///10
        ///3.
        /// </summary>
        internal static string TenthTestInput2 {
            get {
                return ResourceManager.GetString("TenthTestInput2", resourceCulture);
            }
        }
    }
}
